project_id = "ljjdrfyvhnicdeypneke"

[functions.send-email]
verify_jwt = true

[functions.ai-writing-assistant]
verify_jwt = true

[functions.process-scheduled-messages]
verify_jwt = false

[functions.release-posthumous-messages]
verify_jwt = false
